/* TRUNCATION OF THE WORK TABLE */

TRUNCATE TABLE EDW_WORK.TDCUST_REL_PARTY_ADDRESS;

/* CUST_AGMT_CMN_VW SQL QUERY TO CAPTURE BOTH INSERT AND UPDATE RECORDS */
	
INSERT INTO EDW_WORK.TDCUST_REL_PARTY_ADDRESS
	(DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID, PRIMARY_ADDRESS_IND, BEGIN_DT, BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)

SELECT SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID, SRC.PRIMARY_ADDRESS_IND, SRC.BEGIN_DT, SRC.BEGIN_DTM, CURRENT_TIMESTAMP as ROW_PROCESS_DTM, SRC.AUDIT_ID, SRC.LOGICAL_DELETE_IND, SRC.CHECK_SUM, SRC.END_DT, SRC.END_DTM, SRC.SOURCE_SYSTEM_ID, SRC.RESTRICTED_ROW_IND, CASE WHEN ROW_NUMBER() OVER (PARTITION BY SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID, SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID ORDER BY SRC.END_DTM desc, SRC.END_DT desc) = 1 and SRC.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END::BOOLEAN AS CURRENT_ROW_IND
	FROM (
		SELECT DISTINCT HASH_GEN(PREHASH_VALUE(CLEAN_STRING(ATTN_LINE), CLEAN_STRING(AD_L1_TXT), CLEAN_STRING(AD_L2_TXT), CLEAN_STRING(AD_L3_TXT), CLEAN_STRING(AD_L4_TXT),CLEAN_STRING(CITY), CLEAN_STRING(STATE), CLEAN_STRING(ZIP_1_5_NR), CLEAN_STRING(ZIP_6_9_NR), CLEAN_STRING(ZIP_10_13_NR), CLEAN_STRING(SDT1.TRNSLT_FLD_VAL)))::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING(COALESCE(TDC.AD_TYP_CD,'STDA'))))::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(CLEAN_STRING('ECDM')))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
		, HASH_GEN(PREHASH_VALUE(XREF.PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
		, NULL AS PRIMARY_ADDRESS_IND
		, CAST(CUST_AGMT_HIST_FR_DT as date)::date as BEGIN_DT
		, CAST(CUST_AGMT_HIST_FR_DT as date)::timestamp as BEGIN_DTM
		, ADT.AUDIT_ID AS AUDIT_ID
		, 'F'::boolean AS LOGICAL_DELETE_IND
		,  HASH_GEN(PREHASH_VALUE(CLEAN_STRING(NULL)))::UUID AS CHECK_SUM
		, CAST(CUST_AGMT_HIST_TO_DT as date)::date AS END_DT
		, CAST(CUST_AGMT_HIST_TO_DT as date)::timestamp AS END_DTM
		, '205' AS SOURCE_SYSTEM_ID
		, 'F'::boolean AS RESTRICTED_ROW_IND
		FROM(SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'TD_PRTY_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
INNER JOIN TERADATA_HIST.CUST_AGMT_HIST_VW TDC
 	ON XREF.SOR_PARTY_ID = TDC.PRTY_ID
LEFT OUTER JOIN EDW_AUDIT.ETL_BATCH_AUDIT_VW ADT
	ON ADT.BATCH_NAME = 'Customer_to_CIP'
	AND ADT.RECORD_ALIGNER =1
LEFT OUTER JOIN (SELECT SRC_FLD_VAL, TRNSLT_FLD_VAL FROM CIP_SOURCE.SRC_DATA_TRNSLT_VW WHERE SRC_CDE = 'PARTY' AND SRC_FLD_NM = 'CNTRY_NM' AND TRNSLT_FLD_NM = 'COUNTRY NAME') SDT1
 	ON CLEAN_STRING(SDT1.SRC_FLD_VAL) = CLEAN_STRING(TDC.CTRY_CD)
) SRC
LEFT OUTER JOIN (SELECT DIM_ADDRESS_NATURAL_KEY_HASH_UUID::UUID AS DIM_ADDRESS_NATURAL_KEY_HASH_UUID, REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID, CHECK_SUM::UUID AS CHECK_SUM, CURRENT_ROW_IND, END_DT FROM EDW_WORK.TDCUST_REL_PARTY_ADDRESS )TGT
	ON TGT.CURRENT_ROW_IND= TRUE
	AND TGT.END_DT='9999-12-31'
	AND TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID=SRC.DIM_ADDRESS_NATURAL_KEY_HASH_UUID
	AND TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID=SRC.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID
	AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID=SRC.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
	AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID=SRC.DIM_PARTY_NATURAL_KEY_HASH_UUID

WHERE CASE WHEN TGT.DIM_ADDRESS_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_ADDRESS_TYPE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID IS NULL OR TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM <> SRC.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U');
