
/* TRUNCATION OF THE WORK TABLE */
TRUNCATE TABLE EDW_WORK.TDPDCR_REL_PARTY_PHONE;

/* SELECT TO CAPTURE INSERT AND UPDATE RECORDS PDCR PREFERRED */
INSERT INTO EDW_WORK.TDPDCR_REL_PARTY_PHONE (DIM_PHONE_NATURAL_KEY_HASH_UUID, 
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DIM_PARTY_NATURAL_KEY_HASH_UUID, PHONE_INVALID_IND, PRIMARY_PHONE_IND, BEGIN_DT, 
BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, 
END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)
SELECT DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID, 
DRVD.PHONE_INVALID_IND, 
DRVD.PRIMARY_PHONE_IND,
DRVD.BEGIN_DT, 
DRVD.BEGIN_DTM,
CURRENT_TIMESTAMP AS ROW_PROCESS_DTM, 
DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, 
DRVD.CHECK_SUM, 
CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID 
ORDER BY DRVD.END_DTM DESC, DRVD.END_DT DESC) = 1 AND DRVD.END_DT= '9999-12-31' THEN 'T' ELSE 'F' END AS CURRENT_ROW_IND,
DRVD.END_DT, 
DRVD.END_DTM, 
DRVD.SOURCE_SYSTEM_ID, 
DRVD.RESTRICTED_ROW_IND
FROM (SELECT DISTINCT UUID_GEN(PREHASH_VALUE(PHONE_TYPE_CDE)) ::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PHONE_ID))::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_CONTACT_SOURCE_CDE))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID,
NULL AS PHONE_INVALID_IND,
NULL AS PRIMARY_PHONE_IND 
 ,UUID_GEN(PREHASH_VALUE(NULL,NULL))::UUID AS CHECK_SUM
, AUD.AUDIT_ID AS AUDIT_ID
,'207' AS SOURCE_SYSTEM_ID, 'F'::BOOLEAN AS RESTRICTED_ROW_IND
, 'F'::BOOLEAN AS LOGICAL_DELETE_IND
, COALESCE(T1.PDCR_HIST_FR_DT ::DATE,'0001-01-01'::DATE) AS BEGIN_DT
,COALESCE(T1.PDCR_HIST_FR_DT ::TIMESTAMP,'0001-01-01'::TIMESTAMP) AS BEGIN_DTM, 
COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::DATE) AS END_DT
,COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::TIMESTAMP) AS END_DTM
FROM (SELECT DISTINCT CLEAN_STRING('PREFTEL') AS PHONE_TYPE_CDE
, HASH_GEN(PREHASH_VALUE(CLEAN_STRING(PDCR_AGMT.PREFTEL_CTRY_CD_NR),CLEAN_STRING(PDCR_AGMT.PREFTEL_NR_10DIGIT),
 PDCR_AGMT.PREFTEL_XTN_NR)) AS PHONE_ID
, CLEAN_STRING('DSP') AS PARTY_CONTACT_SOURCE_CDE
, XREF.PARTY_ID
, PDCR_AGMT.PDCR_HIST_FR_DT AS PDCR_HIST_FR_DT
, PDCR_AGMT.PDCR_HIST_TO_DT AS PDCR_HIST_TO_DT
FROM TERADATA.PDCR_DEMOGRAPHICS_HIST_VW PDCR_AGMT

JOIN (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'BP_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
ON CLEAN_STRING(PDCR_AGMT.BUSINESS_PARTNER_ID) = XREF.SOR_PARTY_ID
-- WHERE PDCR_AGMT.PDCR_HIST_TO_DT='9999-12-31'
) T1

	LEFT OUTER JOIN EDW_AUDIT.ETL_BATCH_AUDIT_VW AUD
	ON AUD.RECORD_ALIGNER = 1
	AND AUD.BATCH_NAME = 'Producer_to_CIP') DRVD
	
LEFT JOIN (SELECT DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID,
DIM_PHONE_NATURAL_KEY_HASH_UUID::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID,
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID,
END_DT, CURRENT_ROW_IND, CHECK_SUM::UUID AS CHECK_SUM
FROM EDW_WORK.TDPDCR_REL_PARTY_PHONE ) TGT
ON TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID = DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID = DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID = DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID = DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE 
AND TGT.END_DT = '9999-12-31' 

WHERE CASE WHEN TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM  <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U') ;	

/* SELECT TO CAPTURE INSERT AND UPDATE RECORDS PDCR RESIDENTIAL */
INSERT INTO EDW_WORK.TDPDCR_REL_PARTY_PHONE (DIM_PHONE_NATURAL_KEY_HASH_UUID, 
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DIM_PARTY_NATURAL_KEY_HASH_UUID, PHONE_INVALID_IND, PRIMARY_PHONE_IND, BEGIN_DT, 
BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, 
END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)

SELECT DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID, 
DRVD.PHONE_INVALID_IND, 
DRVD.PRIMARY_PHONE_IND,
DRVD.BEGIN_DT, 
DRVD.BEGIN_DTM,
CURRENT_TIMESTAMP AS ROW_PROCESS_DTM, 
DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, 
DRVD.CHECK_SUM, 
CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID 
ORDER BY DRVD.END_DTM DESC, DRVD.END_DT DESC) = 1 AND DRVD.END_DT = '9999-12-31' THEN 'T' ELSE 'F' END AS CURRENT_ROW_IND,
DRVD.END_DT, 
DRVD.END_DTM, 
DRVD.SOURCE_SYSTEM_ID, 
DRVD.RESTRICTED_ROW_IND
FROM
(SELECT UUID_GEN(PREHASH_VALUE(PHONE_TYPE_CDE)) ::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PHONE_ID))::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_CONTACT_SOURCE_CDE))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
,null as PHONE_INVALID_IND,
null as PRIMARY_PHONE_IND,
UUID_GEN(PREHASH_VALUE(NULL,NULL))::UUID AS CHECK_SUM
, AUD.AUDIT_ID AS AUDIT_ID
,'207' AS SOURCE_SYSTEM_ID, 'F'::BOOLEAN AS RESTRICTED_ROW_IND
, 'F'::BOOLEAN AS LOGICAL_DELETE_IND
, COALESCE(T1.PDCR_HIST_FR_DT ::DATE,'0001-01-01'::DATE) AS BEGIN_DT
,COALESCE(T1.PDCR_HIST_FR_DT ::TIMESTAMP,'0001-01-01'::TIMESTAMP) AS BEGIN_DTM, 
COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::DATE) AS END_DT
,COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::TIMESTAMP) AS END_DTM
FROM (
SELECT DISTINCT CLEAN_STRING('RESTEL') AS PHONE_TYPE_CDE
, UUID_GEN(PREHASH_VALUE(CLEAN_STRING(PDCR_AGMT.RESTEL_CTRY_CD_NR),CLEAN_STRING(PDCR_AGMT.RESTEL_NR_10DIGIT),
PDCR_AGMT.RESTEL_XTN_NR)) AS PHONE_ID
, CLEAN_STRING('DSP') AS PARTY_CONTACT_SOURCE_CDE,
XREF.PARTY_ID,
PDCR_AGMT.PDCR_HIST_FR_DT,
PDCR_AGMT.PDCR_HIST_TO_DT
FROM TERADATA.PDCR_DEMOGRAPHICS_HIST_VW PDCR_AGMT

JOIN (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'BP_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
ON CLEAN_STRING(PDCR_AGMT.BUSINESS_PARTNER_ID) = XREF.SOR_PARTY_ID
 --where PDCR_AGMT.PDCR_HIST_TO_DT='9999-12-31'
 ) T1
 
 LEFT OUTER JOIN edw_audit.etl_batch_audit_vw AUD
	ON AUD.record_aligner = 1
	and AUD.batch_name = 'Producer_to_CIP') DRVD

LEFT JOIN (SELECT DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID,
DIM_PHONE_NATURAL_KEY_HASH_UUID::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID,
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID,
END_DT,
CURRENT_ROW_IND,
CHECK_SUM::UUID AS CHECK_SUM
FROM EDW_WORK.TDPDCR_REL_PARTY_PHONE) TGT
ON TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID = DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID = DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID = DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID = DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE  
AND TGT.END_DT = '9999-12-31' 

WHERE CASE WHEN TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM  <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U') ;
	
/* SELECT TO CAPTURE INSERT AND UPDATE RECORDS PDCR preferred fax */
INSERT INTO EDW_WORK.TDPDCR_REL_PARTY_PHONE (DIM_PHONE_NATURAL_KEY_HASH_UUID, 
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DIM_PARTY_NATURAL_KEY_HASH_UUID, PHONE_INVALID_IND, PRIMARY_PHONE_IND, BEGIN_DT, 
BEGIN_DTM, ROW_PROCESS_DTM, AUDIT_ID, LOGICAL_DELETE_IND, CHECK_SUM, CURRENT_ROW_IND, 
END_DT, END_DTM, SOURCE_SYSTEM_ID, RESTRICTED_ROW_IND)

SELECT DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID, 
DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID, 
DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID, 
DRVD.PHONE_INVALID_IND, 
DRVD.PRIMARY_PHONE_IND,
DRVD.BEGIN_DT, 
DRVD.BEGIN_DTM,
CURRENT_TIMESTAMP AS ROW_PROCESS_DTM, 
DRVD.AUDIT_ID, DRVD.LOGICAL_DELETE_IND, 
DRVD.CHECK_SUM,
CASE WHEN ROW_NUMBER() OVER (PARTITION BY DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID 
ORDER BY DRVD.END_DTM DESC, DRVD.END_DT DESC) = 1  AND DRVD.END_DT='9999-12-31' THEN 'T' ELSE 'F' END AS CURRENT_ROW_IND,
DRVD.END_DT, 
DRVD.END_DTM, 
DRVD.SOURCE_SYSTEM_ID, 
DRVD.RESTRICTED_ROW_IND

FROM (SELECT UUID_GEN(PREHASH_VALUE(PHONE_TYPE_CDE)) ::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PHONE_ID))::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_CONTACT_SOURCE_CDE))::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
, UUID_GEN(PREHASH_VALUE(PARTY_ID))::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID
,null as PHONE_INVALID_IND,
null as PRIMARY_PHONE_IND,
UUID_GEN(PREHASH_VALUE(NULL,NULL))::UUID AS CHECK_SUM
, AUD.AUDIT_ID AS AUDIT_ID
,'207' AS SOURCE_SYSTEM_ID, 'F'::BOOLEAN AS RESTRICTED_ROW_IND
, 'F'::BOOLEAN AS LOGICAL_DELETE_IND
, COALESCE(T1.PDCR_HIST_FR_DT ::DATE,'0001-01-01'::DATE) AS BEGIN_DT
,COALESCE(T1.PDCR_HIST_FR_DT ::TIMESTAMP,'0001-01-01'::TIMESTAMP) AS BEGIN_DTM, 
COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::DATE) AS END_DT
,COALESCE(T1.PDCR_HIST_TO_DT ::DATE,'9999-12-31'::TIMESTAMP) AS END_DTM
from 
(SELECT DISTINCT CLEAN_STRING('PREFAX') AS PHONE_TYPE_CDE
, UUID_GEN(PREHASH_VALUE(CLEAN_STRING(PDCR_AGMT.PREFAX_TEL_CTRY_CD_NR),
CLEAN_STRING(PDCR_AGMT.PREFAX_TEL_NR_10DIGIT))) AS PHONE_ID
, CLEAN_STRING('DSP') AS PARTY_CONTACT_SOURCE_CDE,
XREF.PARTY_ID,
PDCR_AGMT.PDCR_HIST_FR_DT,
PDCR_AGMT.PDCR_HIST_TO_DT
FROM TERADATA.PDCR_DEMOGRAPHICS_HIST_VW PDCR_AGMT

JOIN (SELECT DISTINCT PARTY_ID, SOR_PARTY_ID FROM EDW.PARTY_MASTER_OF_MASTERS_XREF WHERE PARTY_ID_TYPE_CDE = 'BP_ID' AND LOGICAL_DELETE_IND = 'F'::BOOLEAN) XREF
ON CLEAN_STRING(PDCR_AGMT.BUSINESS_PARTNER_ID) = XREF.SOR_PARTY_ID
--whre PDCR_AGMT.PDCR_HIST_TO_DT='9999-12-31'  
) t1
 
 LEFT OUTER JOIN edw_audit.etl_batch_audit_vw AUD
	ON AUD.record_aligner = 1
	and AUD.batch_name = 'Producer_to_CIP') DRVD

LEFT JOIN (SELECT DIM_PARTY_NATURAL_KEY_HASH_UUID::UUID AS DIM_PARTY_NATURAL_KEY_HASH_UUID ,
DIM_PHONE_NATURAL_KEY_HASH_UUID::UUID AS DIM_PHONE_NATURAL_KEY_HASH_UUID,
REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID::UUID AS REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID,
REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID::UUID AS REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID,
END_DT,
CURRENT_ROW_IND,
CHECK_SUM::UUID AS CHECK_SUM
FROM EDW_WORK.TDPDCR_REL_PARTY_PHONE) TGT

ON TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID = DRVD.DIM_PHONE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID = DRVD.REF_PHONE_TYPE_NATURAL_KEY_HASH_UUID
AND TGT.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID = DRVD.REF_PARTY_CONTACT_SOURCE_NATURAL_KEY_HASH_UUID
AND TGT.DIM_PARTY_NATURAL_KEY_HASH_UUID = DRVD.DIM_PARTY_NATURAL_KEY_HASH_UUID
AND TGT.CURRENT_ROW_IND = TRUE 
AND TGT.END_DT = '9999-12-31' 

WHERE CASE WHEN TGT.DIM_PHONE_NATURAL_KEY_HASH_UUID IS NULL THEN 'I'
	WHEN TGT.CHECK_SUM  <> DRVD.CHECK_SUM THEN 'U'
	ELSE 'D' END IN ('I','U') ;
 
